version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'PeliculaDB'
      MYSQL_USER: 'Admin'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    volumes:
      - crud:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initbd.d
    
  nodejs:
   image: jadelpozo2696/node-web-app:lab5_v14
   ports:
      - '3307:3306'
      - '3000:3000'
   expose:
      - '3000'
   depends_on:
     - db
   networks:
      vpcbr:
        ipv4_address: 10.5.0.6
# Names our volume
volumes:
  crud:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
